import {
  AgentRun,
  ApprovalRequest,
  AuditEvent,
  DashboardData,
  EmergencyResource,
  EvidenceItem,
  FamilyMember,
  Household,
  Incident,
  SourceRecord,
  TimelineEvent,
  VoiceCall,
} from '@/lib/types';

const now = () => new Date().toISOString();
const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const demoHousehold: Household = {
  id: 'hh_demo_santa_rosa',
  ownerId: 'demo-owner',
  name: 'Rivera Household',
  homeAddress: 'Fictional address near Santa Rosa, CA',
  region: 'Sonoma County, California',
  emergencyPreferences: {
    evacuationMode: 'leave_now',
    accessibilityNotes: 'Wheelchair access needed for Mark. Keep medical battery pack charged.',
    supplies: ['72-hour go bag', 'N95 masks', 'battery pack', 'pet carrier'],
    vehicles: ['Blue SUV', 'neighbor pickup option'],
    pets: ['Leo - dog'],
    medicalDependencies: ['portable oxygen battery', 'wheelchair access'],
  },
  emergencyContacts: [
    { id: 'ec_1', name: 'Sarah Rivera', relationship: 'Owner', phone: '+15555550101', optInVoice: true },
    { id: 'ec_2', name: 'Mark Rivera', relationship: 'Parent', phone: '+15555550102', optInVoice: true },
  ],
  outboundVoiceConsent: true,
  createdAt: minutesAgo(90),
  updatedAt: now(),
};

export const demoMembers: FamilyMember[] = [
  {
    id: 'mem_sarah',
    householdId: demoHousehold.id,
    name: 'Sarah (Mom)',
    role: 'Parent',
    status: 'safe',
    location: 'Work - Downtown Santa Rosa',
    locationNote: 'Can drive, has go bag.',
    needs: [],
    contactMethod: 'Vapi call + SMS',
    phone: '+15555550101',
    batteryLevel: 85,
    lastCheckIn: minutesAgo(12),
    voiceConsent: true,
    updatedBy: 'demo',
  },
  {
    id: 'mem_mark',
    householdId: demoHousehold.id,
    name: 'Mark (Dad)',
    role: 'Parent',
    status: 'unknown',
    location: 'North Campus school pickup loop',
    locationNote: 'May need accessible pickup route.',
    needs: ['Wheelchair access', 'medical battery'],
    contactMethod: 'Vapi outbound call',
    phone: '+15555550102',
    batteryLevel: 15,
    lastCheckIn: minutesAgo(48),
    voiceConsent: true,
    updatedBy: 'demo',
  },
  {
    id: 'mem_leo',
    householdId: demoHousehold.id,
    name: 'Leo',
    role: 'Dog',
    status: 'needs_pickup',
    location: 'Home',
    locationNote: 'Pet carrier in garage.',
    needs: ['Pet carrier', 'animal shelter accepts dogs'],
    contactMethod: 'Tracked by Sarah',
    pets: ['Leo'],
    lastCheckIn: minutesAgo(50),
    voiceConsent: false,
    updatedBy: 'demo',
  },
];

export const demoIncident: Incident = {
  id: 'inc_santa_rosa_demo',
  householdId: demoHousehold.id,
  name: 'Santa Rosa Wildfire Monitor',
  externalId: 'demo-cal-fire-sonoma',
  location: 'Northeast of Santa Rosa',
  status: 'active',
  evacuationStatus: 'warning',
  latitude: 38.48,
  longitude: -122.65,
  monitoredSources: ['CAL FIRE', 'Sonoma County Emergency', 'PG&E outage center', 'Caltrans quickmap'],
  lastRefreshedAt: minutesAgo(4),
  ghostSnapshotId: 'ghost_demo_fork_inc_santa_rosa',
};

export const demoSources: SourceRecord[] = [
  {
    id: 'src_calfire',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    url: 'https://www.fire.ca.gov/incidents',
    title: 'CAL FIRE Incidents',
    sourceType: 'official',
    trustScore: 0.98,
    fetchedAt: minutesAgo(5),
    extractedSummary: 'Official incident page checked for active Sonoma County wildfire conditions.',
  },
  {
    id: 'src_sonoma',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    url: 'https://socoemergency.org/',
    title: 'Sonoma County Emergency',
    sourceType: 'official',
    trustScore: 0.96,
    fetchedAt: minutesAgo(5),
    extractedSummary: 'County emergency page checked for evacuation notices and shelter guidance.',
  },
  {
    id: 'src_pge',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    url: 'https://pgealerts.alerts.pge.com/outage-tools/outage-map/',
    title: 'PG&E Outage Map',
    sourceType: 'utility',
    trustScore: 0.88,
    fetchedAt: minutesAgo(7),
    extractedSummary: 'Utility outage source checked for power risk near household and shelters.',
  },
];

export const demoResources: EmergencyResource[] = [
  {
    id: 'res_shelter',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    type: 'shelter',
    name: 'Santa Rosa High School Shelter',
    address: '123 Main St, Santa Rosa, CA',
    distance: '3.2 mi',
    status: 'open',
    capacity: '45% full',
    acceptsPets: false,
    accessibility: ['wheelchair ramp', 'medical charging area'],
    url: 'https://socoemergency.org/',
    sourceId: 'src_sonoma',
    confidence: 0.82,
    latitude: 38.42,
    longitude: -122.69,
  },
  {
    id: 'res_pet',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    type: 'animal_shelter',
    name: 'County Animal Rescue Intake',
    address: '456 Oak Rd, Santa Rosa, CA',
    distance: '4.5 mi',
    status: 'open',
    capacity: '60% full',
    acceptsPets: true,
    url: 'https://socoemergency.org/',
    sourceId: 'src_sonoma',
    confidence: 0.78,
    latitude: 38.45,
    longitude: -122.74,
  },
  {
    id: 'res_road',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    type: 'road_closure',
    name: 'Avoid Highway 12 eastbound',
    address: 'Highway 12 corridor',
    distance: '2.1 mi',
    status: 'unknown',
    url: 'https://quickmap.dot.ca.gov/',
    sourceId: 'src_sonoma',
    confidence: 0.7,
    latitude: 38.46,
    longitude: -122.67,
  },
  {
    id: 'res_charging',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    type: 'charging',
    name: 'Community Center Power Station',
    address: '789 Pine Ln, Santa Rosa, CA',
    distance: '1.2 mi',
    status: 'open',
    capacity: 'medical devices prioritized',
    sourceId: 'src_pge',
    confidence: 0.74,
    latitude: 38.47,
    longitude: -122.7,
  },
];

export const demoTimeline: TimelineEvent[] = [
  {
    id: 'tl_alert',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    timestamp: minutesAgo(65),
    source: 'CAL FIRE',
    content: 'Official incident source checked for new wildfire activity near Sonoma County.',
    type: 'alert',
    sourceUrl: 'https://www.fire.ca.gov/incidents',
  },
  {
    id: 'tl_agent',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    timestamp: minutesAgo(10),
    source: 'TinyFish Agent',
    content: 'Found official county guidance, shelter options, one road risk, and one utility source.',
    type: 'agent',
  },
  {
    id: 'tl_ghost',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    timestamp: minutesAgo(8),
    source: 'Ghost Snapshot',
    content: 'Created isolated incident snapshot for reachability simulation.',
    type: 'system',
  },
];

export const demoApprovals: ApprovalRequest[] = [
  {
    id: 'ap_family_alert',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    actionType: 'send_family_alert',
    title: 'Send family evacuation update',
    description: 'Send the current source-backed plan to opted-in household contacts.',
    riskLevel: 'low',
    preparedPayload: {
      message:
        'Wildfire monitor recommends leaving now. Shelter option: Santa Rosa High School Shelter. Avoid Highway 12 eastbound. Bring battery pack and pet carrier.',
      recipients: ['Sarah Rivera', 'Mark Rivera'],
    },
    status: 'pending',
    preparedAt: minutesAgo(6),
  },
  {
    id: 'ap_voice_mark',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    actionType: 'place_outbound_voice_call',
    title: 'Call Mark for safety check-in',
    description: 'Vapi outbound call asks Mark to say safe, need pickup, need medical help, or unreachable.',
    riskLevel: 'medium',
    preparedPayload: { memberId: 'mem_mark', phone: '+15555550102' },
    status: 'pending',
    preparedAt: minutesAgo(5),
  },
  {
    id: 'ap_pet_draft',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    actionType: 'prepare_shelter_contact',
    title: 'Prepare animal shelter contact draft',
    description: 'Prepare intake details for Leo. MVP does not submit external shelter forms automatically.',
    riskLevel: 'medium',
    preparedPayload: { petName: 'Leo', owner: 'Sarah Rivera', needs: ['pet carrier'] },
    status: 'draft',
    preparedAt: minutesAgo(5),
  },
];

export const demoEvidence: EvidenceItem[] = [
  {
    id: 'ev_calfire',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    timestamp: minutesAgo(5),
    kind: 'source_url',
    sourceUrl: 'https://www.fire.ca.gov/incidents',
    extractedData: 'Official incident page checked and stored with timestamp.',
    trustLevel: 'Official government/emergency source',
  },
  {
    id: 'ev_audit',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    timestamp: minutesAgo(4),
    kind: 'audit_trace',
    extractedData: 'Guild-style audit trace created for read_web_sources and prepare_action scopes.',
    trustLevel: 'System audit',
    guildTraceId: 'guild_demo_trace_monitor',
  },
];

export const demoAuditEvents: AuditEvent[] = [
  {
    id: 'audit_read',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    guildRunId: 'guild_demo_run_monitor',
    actor: 'wildfire_family_response_agent',
    permissionScope: 'read_web_sources',
    toolCall: 'tinyfish.search',
    decision: 'allowed',
    outcome: 'Official and utility sources discovered.',
    createdAt: minutesAgo(10),
  },
  {
    id: 'audit_prepare',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    guildRunId: 'guild_demo_run_monitor',
    actor: 'wildfire_family_response_agent',
    permissionScope: 'prepare_action',
    toolCall: 'approval_requests.insert',
    decision: 'requires_approval',
    outcome: 'Three approval-gated actions prepared.',
    createdAt: minutesAgo(5),
  },
];

export const demoVoiceCalls: VoiceCall[] = [
  {
    id: 'vc_demo_web',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    direction: 'web',
    memberName: 'Owner',
    status: 'completed',
    transcript: 'Where should we go? Assistant answered from current shelter and road source records.',
    outcome: 'Briefing delivered from current plan.',
    durationSeconds: 42,
    startedAt: minutesAgo(3),
    endedAt: minutesAgo(2),
  },
];

export const demoAgentRuns: AgentRun[] = [
  {
    id: 'run_tinyfish_monitor',
    householdId: demoHousehold.id,
    incidentId: demoIncident.id,
    task: 'Monitor wildfire near Santa Rosa household address',
    status: 'completed',
    sponsorTool: 'TinyFish Agent SSE',
    startedAt: minutesAgo(11),
    endedAt: minutesAgo(5),
    resultSummary: 'Found official sources, resources, road risk, and approval-gated next actions.',
  },
];

export function createDemoDashboardData(): DashboardData {
  return {
    mode: 'demo',
    household: demoHousehold,
    members: [...demoMembers],
    incident: demoIncident,
    sources: [...demoSources],
    resources: [...demoResources],
    approvals: [...demoApprovals],
    timeline: [...demoTimeline],
    evidence: [...demoEvidence],
    auditEvents: [...demoAuditEvents],
    voiceCalls: [...demoVoiceCalls],
    agentRuns: [...demoAgentRuns],
    nextActions: [
      'Leave now if local officials confirm an evacuation order or conditions worsen.',
      'Use Santa Rosa High School Shelter for wheelchair access; use County Animal Rescue for Leo.',
      'Avoid Highway 12 eastbound until Caltrans or county sources confirm it is clear.',
    ],
  };
}
